### ISSUE TITLE
Move buffered-spawn out of organization

### ISSUE THREAD

**Issue by sheerun** [IndigoUnited/buffered-spawn#6]
Hey @satazor 

I see buffered-spawn is not a dependency of any of bower projects. The only dependants are: `brackets-npm-registry, foundry, generator-mozu-theme, image-diff, nio-engine, nio-pack, npm-check, phantomjssmith, pog, preheat, quick-git-hits`

Maybe it would a good idea if we transfer the repo to you?

Adam

**Comment by satazor** [comment]
Yes, agree.
